In [5]:
import numpy as np
from scipy.linalg import lu

#2. Найдите псевдорешение:
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15


In [24]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = [1, 7, 12, 7, 15]
# Как показала проверка, эта система не имеет решений, буду искать псевдорешение
np.linalg.lstsq(A, B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

#4 Вычислите LU-разложение матрицы:
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей

In [19]:
A = np.array([[1, 2, 3], [2, 16, 21], [4,26, 73]])
P, L, U = scipy.linalg.lu(A)
print(P, L, U)


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] [[ 1.          0.          0.        ]
 [ 0.25        1.          0.        ]
 [ 0.5        -0.66666667  1.        ]] [[  4.          26.          73.        ]
 [  0.          -4.5        -15.25      ]
 [  0.           0.         -25.66666667]]


In [22]:
# Заранее придумал решение системы: 1, 1 и -1. Тогда B:
B = [[0], [-4], [-51]]
np.linalg.solve(A, B)

array([[ 1.25108225],
       [ 1.12770563],
       [-1.16883117]])

#6. Найдите одно из псевдорешений вырожденной системы:


In [26]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = [2, 5, 1]
np.linalg.lstsq(A, B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([-1.80555556, -0.05555556,  1.69444444]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 1.47280825e-16]))