### ДЗ 2. Матрицы, определители.

In [1]:
import numpy as np

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица AB\n{np.dot(A, B)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [14]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица AB\n{3*A -2*B + 4*C}')

Матрица AB
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


In [20]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица At\n{A.T}')
print(f'Матрица A*At\n{np.dot(A, A.T)}')
print(f'Матрица At*A\n{np.dot(A.T, A)}')


Матрица At
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*At
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица At*A
[[45  0]
 [ 0 14]]



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [23]:
from random import randrange

def matrix_generate(n):  #Генерация квадратной матрицы размером n
    m = []
    for _ in range(n):
        x = [randrange(0, 10) for i in range(n)]
        m.append(x)
    return(m)

def matrix_mult(n = 3):  #Переменожение квадратных матриц
    
    a = matrix_generate(n)
    b = matrix_generate(n)
    print('Первая матрица', a)
    print('Вторая матрица', b)
    mmult = []
    for i in range(n):
        mmult.append([randrange(0, 1) for i in range(n)])
    
        
            
    for i in range(n):
        for j in range(n):
            total = 0
            for k in range(n):
                total += a[i][k] * b[k][j]
            mmult[i][j] = total

    print('Результат умножения', mmult)
    

matrix_mult(3)

Первая матрица [[4, 8, 2], [8, 3, 5], [2, 8, 7]]
Вторая матрица [[2, 7, 1], [7, 4, 6], [0, 5, 8]]
Результат умножения [[64, 70, 68], [37, 93, 66], [60, 81, 106]]


__2.1__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [ ]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [22]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


 в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.2__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$ <br>
   Согласно свойству: для квадратных матриц одинакового размера<br>

$det(AB)=detA\cdot detB.$<br> Поэтому
   
   $det(A^{2})$ = $det(A)*det(A)$ = 16
    
   б) $det(A^{T})$;<br>
   Определитель транспонированной матрицы равен определителю исходной:

$detA^{T}=detA.$ = 16


    
   в) $det(2A)$.
  Есть свойство, что Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. Значит, для матрицы порядка n, n строк будут умножены на 2, и определитель увелится в 2^{n} раз.
  
   $det(2A) = detA *2^{n} = 16$ <br><br>
   Проверим.

In [29]:
a = np.array([[5, 2], [3 ,2 ]])
b = np.dot(a, a)
c = 2*a
print(f'Матрица:\n{b}')
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')
print(f'Определитель:\n{np.linalg.det(a.T):.0f}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[31 14]
 [21 10]]
Матрица:
[[10  4]
 [ 6  4]]
Определитель:
16
Определитель:
4
Определитель:
16


__2.3__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = 
-2\begin{vmatrix}
-14 & 6\\  
7 & 13 \\ 
\end{vmatrix}
7\begin{vmatrix}
4 & 6\\  
-3 & 13 \\ 
\end{vmatrix} + 
-3\begin{vmatrix}
4 & -14\\  
-3 & 7\\ 
\end{vmatrix} = -2\cdot(-14\cdot13-6\cdot7)
7\cdot(4\cdot13 + 3\cdot6) + (-3)\cdot(4\cdot7 - (-3)\cdot(-14)) = 0.$$
<br>
Определитель матрицы равен 0, поэтому матрица вырожденная

In [32]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
0


__2.4__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

3-я строка является суммой первой и второй строк, ее можно отбросить. Остается <br>
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$ <br>
Из первой строки вычтем вторую:
$\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1
\end{pmatrix};$ <br>
Таким образом, ранг матрицы равен 2.
Проверим:


In [33]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]
a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$ <br> Третья строка является суммой первой и второй, удалим ее. Переставим нижнюю строку наверх. <br>
$\begin{pmatrix} 
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2
\end{pmatrix}.$<br> Вычтем из третей строки вторую <br>
$\begin{pmatrix} 
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1
\end{pmatrix}.$<br>Ранг матрицы равен 3

In [35]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
w = [2, 3, 5, 6]
a = np.array([x, y, z, w])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
