In [2]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$





 __Решение__

найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

Из этого будет следовать, что 

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-1\cdot x_{1}-6\cdot x_{2}= \lambda \cdot x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= \lambda \cdot x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
-1\cdot x_{1}- \lambda \cdot x_{1} - 6\cdot x_{2}  = 0, \\
2 \cdot x_{1}+ 6\cdot x_{2} - \lambda x_{2} = 0;
\end{cases}$$ 

Теперь найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(1+\lambda)(\lambda - 6)+ 12 =0,$$

$$(\lambda)^{2} - 5\cdot \lambda +6  =0,$$

$$\lambda=2.$$
$$\lambda=3.$$

$$\begin{cases}
-1\cdot x_{1} - 2\cdot x_{2}  = 0, \\
1\cdot x_{1}+ 2\cdot x_{2}  = 0;
\end{cases}$$  для $$\lambda=2.$$

и собственный вектор вида $\begin{pmatrix}
2\\ 
-1
\end{pmatrix}$

$$\begin{cases}
-2\cdot x_{1} - 3\cdot x_{2}  = 0, \\
2\cdot x_{1}+ 3\cdot x_{2}  = 0;
\end{cases}$$  для $$\lambda=3.$$

и собственный вектор вида $\begin{pmatrix}
3\\ 
-2
\end{pmatrix}$

In [7]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

 __Решение__

найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, 
$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\begin{pmatrix}
-x_{1}\\ 
-x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$

и $\lambda = -1 $

Таким образом, любой вектор отвечает требованию собственного вектора для данного оператора.



__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

 __Решение__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Решение нашлось, следовательно, вектор $x=(1,1)$  является собственным вектором линейного оператора, заданного матрицей $A$.

In [6]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора. Аналогично методике из предыдущего примера получим:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=12
\end{cases}
\Rightarrow
\lambda=-3.$$

Таким образом, вектор $x=(3,-3,4)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=-3.$

In [5]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
