### Линейные нормированные пространства

Практическое задание

__1.__ Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

Решение:  
$$f_{4}(x)=f_{3}(x)-f_{2}(x)- f_{1}(x)$$
поэтому векторы линейно зависимы




__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$

Решение:
$$f_{4}(x)=f_{3}(x)+2f_{2}(x)+0,5 f_{1}(x)$$
поэтому векторы линейно зависимы


__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

Решение: 

$$x=(2, 3, 5)=(2,0,0)+(0, 3, 0)+(0, 0, 5)=1\cdot(2, 0, 0)+3\cdot(0, 1, 0)+0.5\cdot(0, 0, 10)=2b_{2}+3b_{3}+0.5b_{1},$$

то есть координатами вектора $x$ в заданном базисе являются $0.5$, $2$, $3$.

__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;
   
   Решение: 


    координатами вектора 
 $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$ в базисе $1$, $x$, $x^{2}$ являются $2$, $-2$, $3$.

   б) в базисе $x^{2}$, $x-1$, $1$.
    
координатами вектора $$3x^{2}-2x+2\in\mathbb{R}^{3}[x]$$ в базисе  $x^{2}$, $x-1$, $1$ являются $3$, $-2$, $0$.
    


__5. Установить, является ли линейным подпространством:__

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

__Решение__

Имеется три варианта для этих векторов:
$$(0, a, b) , (a, 0, b) и (0, 0, b). Однако третий является частным случаем первого и второго множества, так что его можно не проверять.

Проверим первое подпространство:
$$(0, a, b)+(0, c, d) = (0, a+c, b+d),$$ $$\alpha\cdot (0, a, b) = (0, \alpha a, \alpha b).$$

Полученные векторы также принадлежат указанному в задании множеству всех векторов вида $(0, a, b)$, то есть данное множество является подпространством линейного пространства $\mathbb{R}^{3}$.
Аналогичное доказательство будет для второго подпространства.
Поэтому совокупность всех этих подпространств также будет являться линейной.

б) все векторы, являющиеся линейными комбинациями данных векторов {𝑢1,𝑢2,...,𝑢𝑛}
.

__2.1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$




In [2]:
import numpy as np

In [32]:
x1 = np.array([0, -3, 6])
y1 = np.array([-4, 7, 9])
print(f'Скалярное произведение :\n{np.dot(x1, y1)}')


Скалярное произведение :
33
l1 норма вектора b:
9.0
l1 норма вектора b:
20.0


In [31]:
x2 = np.array([7, -4, 0, 1])
y2 = np.array([-3, 1, 11, 2])
print(f'Скалярное произведение :\n{np.dot(x2, y2)}')


Скалярное произведение :
-23
Скалярное произведение :
-23


__2.2__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

In [3]:
from numpy.linalg import norm

Зададим вектор $a=(1,2,-3)$:

In [8]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

In [10]:
print(f'l1 норма вектора a:\n{norm(a, ord=1)}')
print(f'l1 норма вектора b:\n{norm(b, ord=1)}')

l1 норма вектора a:
10.0
l1 норма вектора b:
10.0


In [11]:
print(f'l2 норма вектора a:\n{norm(a, ord=2)}')
print(f'l2 норма вектора b:\n{norm(b, ord=2)}')

l2 норма вектора a:
6.0
l2 норма вектора b:
13.0


In [12]:
cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.2f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.2f}')

Косинус угла между a и b: 0.90
Угол между a и b: 0.46



__2.3__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?

Требуется проверить 4 аксиомы:
1) (𝑥,𝑦)=(𝑦,𝑥);
2) (𝜆𝑥,𝑦)=𝜆(𝑥,𝑦);
3) (𝑥1+𝑥2,𝑦)=(𝑥1,𝑦)+(𝑥2,𝑦);
4) (𝑥,𝑥)≥0, причем (𝑥,𝑥)=0⇔𝑥=0.


а) произведение длин векторов;<br>
длины векторов это обычные числа, поэтому от перестановки их ничего не изменится<br>
аналогично для второй<br>
для чисел эта аксиома соблюдается<br>
число в квадрате всегда больше равно 0<br>
Аналогично можно сказать, вспомнив про аксиомы про нормированное пространство:<br>
1) $\left\|x\right\|\geq0$, причем $\left\|x\right\|=0\Leftrightarrow x=0;$<br>
2) $\left\|\lambda x\right\|$ = $|\lambda|\left\|x\right\|$;<br>
3) $\left\| x + y \right\|$ = $\left\|x\right\|$ + $\left\|y\right\|$.<br>
Ответ: пространство будет евклидовым

б) утроенное обычное скалярное произведение векторов?<br>
1)  3(𝑥,𝑦)=3(𝑦,𝑥) = 3*x*y*cos(a)<br>
2)  3(𝜆𝑥,𝑦)=3𝜆(𝑥,𝑦) = 3*𝜆*x*y*cos(a)<br>
3) 3(𝑥1+𝑥2,𝑦)= 3(𝑥1+𝑥2)𝑦*cos(a) =3(𝑥1,𝑦)+3(𝑥2,𝑦);
4) 3(𝑥,𝑥)≥0, причем 3(𝑥,𝑥)=0⇔𝑥=0.
Ответ: пространство будет евклидовым

__2.4__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>

In [10]:
x1 = np.array([1, 0, 0])
y1 = np.array([0, 0, 1])
print(f'Скалярное произведение :\n{np.dot(x1, y1)}')
print('x1 и y1 образуют ортонормированный базис')

Скалярное произведение :
0
x1 и y1 образуют ортонормированный базис


б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>

In [25]:
x2 = np.array([1/np.sqrt(2), -1/np.sqrt(2), 0])
y2 = np.array([1/np.sqrt(2), 1/np.sqrt(2), 0])
z2 = np.array([0, 0, 1])
print('x1 и y1 и z1 не образуют ортонормированный базис')
print(f'Скалярное произведение x2, y2 :\n{np.dot(x2, y2)}')
print(f'Скалярное произведение z2, y2:\n{np.dot(z2, y2)}')
print(f'Скалярное произведение x2, z2 :\n{np.dot(x2, z2)}')
print(f'Скалярное произведение x2, y2, z2 :\n{np.dot(x2, np.dot(y2, z2))}')
print('x2 и y2 и z2 образуют ортонормированный базис')
np.dot(np.dot(x2, y2), z2)


x1 и y1 и z1 не образуют ортонормированный базис
Скалярное произведение x2, y2 :
0.0
Скалярное произведение z2, y2:
0.0
Скалярное произведение x2, z2 :
0.0
Скалярное произведение x2, y2, z2 :
[0. 0. 0.]
x2 и y2 и z2 образуют ортонормированный базис


array([0., 0., 0.])

в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>

In [29]:
x3 = np.array([1/2, -1/2, 0])
y3 = np.array([0,1/2, 1/2])
z3 = np.array([0, 0, 1])
print(np.dot(np.dot(x3, y3), z3))
print('x3 и y3 и z3 не образуют ортонормированный базис')

[ 0.    0.   -0.25]
x3 и y3 и z3 не образуют ортонормированный базис


г) $(1,0,0),(0,1,0),(0,0,1)?$ 

In [ ]:
здесь очевидно, что базис ортонормирован

__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

__2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.


__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?
   
   
__4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

## Литература

## Дополнительные материалы

1. [Манхэттенская метрика](https://ru.wikipedia.org/wiki/Расстояние_городских_кварталов).

2. [Евклидова метрика](https://ru.wikipedia.org/wiki/Евклидова_метрика).

3. [Скалярное произведение в Python](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html#matrix-and-vector-products).

4. [Документация по нормам в NumPy](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.norm.html)

5. [Документация по метрикам в SciPy](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.spatial.distance.cdist.html)