In [7]:
import numpy as np
import pandas as pd
from scipy import stats

Задача 1

Даны значения величины заработной платы заемщиков банка (salary) и значения их поведенческого кредитного скоринга (scoring):

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

    Найдите ковариацию этих двух величин: сначала без использования специальных функций, а затем с помощью функции numpy.cov. Полученные значения должны быть равны.
    Найдите коэффициент корреляции Пирсона: с помощью ковариации и средних квадратических отклонений двух признаков, а затем с помощью специальных функций из библиотек numpy и pandas.



In [24]:
salary = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
scoring = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])


salary_mean = salary.sum()/(salary.shape[0]-1)
scoring_mean = scoring.sum()/(scoring.shape[0]-1)

cov1 = ((salary - salary_mean) * (scoring - scoring_mean)).mean()
cov1

10046.529629629631

In [26]:
cov2 = np.cov(salary, scoring)
cov2

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [31]:
corr = cov2/(salary.std(ddof=1) * scoring.std(ddof=1))
corr

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [16]:
np.corrcoef(salary, scoring)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Задача 2

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111

Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [12]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
alpha = 0.05
n = iq.shape[0]
mean = iq.mean()
std = iq.std(ddof=1)
t = stats.t.ppf(1 - alpha / 2, df=n - 1)
(mean - t * std / np.sqrt(n), mean + t * std / np.sqrt(n))

(110.55608365158724, 125.64391634841274)

Задача 3

Известно, что рост футболистов в сборной распределён нормально с известной дисперсией 25. На выборке объёма 27 выборочное среднее составило 174.2. Найдите доверительный интервал для математического ожидания с надёжностью 0.95.

In [14]:
alpha = 0.05
n = 25
std = 5
mean = 174.2
#Рост считается распределенным нормально
#Тогда математическое ожидание должно быть в интервале
(mean - 2 * std/np.sqrt(n), mean + 2 * std/np.sqrt(n))

(172.2, 176.2)

Задача 4

Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее в комментарии к Практическому заданию.

Анализ данных с Airbnb
К сожалению, не нашел данных по России, так что будет западный город.

Описательная статистика - графики, влияние величин на общую доходность апартаментов, как зависит число занятых дней от цены, дисперсионный анализ, по каким апартаментам имеется дефицит или переизбыток.
Проверить, каким распределениямм подчиняются характеристики.
Предиктивная аналитика - предсказать изменения на рынке -объем предложения разных видов апартаментов и цены, если известны данные за несколько лет.

